name: ruminate
description: "Ruminate is an app designed to help people with self-reflection so they can get to know themselves and find their happiness."
publish_to: "none"
version: 0.1.0

environment:
  sdk: ^3.9.2

dependencies:
  archive: ^4.0.7
  firebase_auth: ^6.1.3
  firebase_core: ^4.3.0
  fl_chart: ^1.1.1
  flutter:
    sdk: flutter
  flutter_riverpod: ^3.0.3
  freezed_annotation: ^3.1.0
  go_router: ^16.2.4
  intl: ^0.20.2
  json_annotation: ^4.9.0
  mocktail: ^1.0.4
  path_provider: ^2.1.5
  path_provider_platform_interface: ^2.1.2
  share_plus: ^12.0.1
  shared_preferences: ^2.5.4

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  build_runner: ^2.7.1
  freezed: ^3.2.3
  json_serializable: ^6.11.1


flutter:
  uses-material-design: true
