name: ruminate
description: "Ruminate is an app designed to help people with self-reflection so they can get to know themselves and find their happiness."
publish_to: "none"
version: 0.1.0

environment:
  sdk: ^3.9.2

dependencies:
  flutter:
    sdk: flutter
  flutter_riverpod: ^3.0.3
  freezed_annotation: ^3.1.0
  go_router: ^16.2.4
  json_annotation: ^4.9.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  build_runner: ^2.7.1
  freezed: ^3.2.3
  json_serializable: ^6.11.1


flutter:
  uses-material-design: true
