name: ruminate
description: "Ruminate is an app designed to help people with self-reflection so they can get to know themselves and find their happiness."
publish_to: "none"
version: 0.1.0

environment:
  sdk: ^3.9.0-172.0.dev

dependencies:
  flutter:
    sdk: flutter
  flutter_riverpod: ^3.0.3
  go_router: ^16.2.4

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
